config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"

  resources :cocktails do
    resources :doses, only: [:new, :create, :index]
  end

  resources :cocktails
  resources :doses, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses #allows Cocktail to access ingredient using cocktail.ingredient.name, and not require cocktail.dose.ingredient.name

  validates :name, presence: true, uniqueness: true, allow_blank: false

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true

  validates_uniqueness_of :ingredient_id, :scope => [:cocktail_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  before_action :set_dose, only: [:destroy]

  def index
    @cocktails = Cocktail.all

    # To find the dose in the cocktail
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if  @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail), notice: 'Cocktail successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_cocktail, only: [:new, :create]
  before_action :set_dose, only: [:destroy, :edit, :update]

  def new
    # @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.create(dose_params)

    #link the dose to the cocktail
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @dose.update(dose_params)
      redirect_to cocktail_path(@dose.cocktail), notice: 'Dose successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:amount, :description, :cocktail_id, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <% if @cocktail.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @cocktail.errors.full_messages.each do |message| %>
          <li><% message %></li>
         <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <p></p>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit Cocktail Details</h1>

<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/index.html.erb
<h1 class="text-center"><span id="banner-typed-text"></span></h1>

<div class="container">
    <% @cocktails.each do |cocktail| %>
      <tr>
        <div class="col-xs-12 col-sm-4">
          <div class="card my-card">
            <%= cocktail.name %>
            <<div class="card-btns">
              <%=  link_to 'Show', cocktail, class: "btn my-button"%>
              <%=  link_to 'Edit', edit_cocktail_path(cocktail), class: "btn my-button"%>
              <%=  link_to 'Destroy', cocktail, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn my-button"%>
            </div>
          </div>
        </div>
      </tr>
    <% end %>
  </tbody>
</div>

<%= link_to "New Cocktail", new_cocktail_path, class: "btn btn-primary" %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to "Back", cocktails_path %>

app/views/cocktails/show.html.erb
<h1>Cocktail: <%= @cocktail.name %></h1>

<h3>Name: <%= @cocktail.name %></h3>

<% @cocktail.doses.each do |dose| %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="card">
          Ingredient: <%= dose.ingredient.name %>; Amount: <%= dose.amount %>0 ml
          <%=  link_to 'Edit', edit_dose_path(dose), class: "my-button" %>
          <%=  link_to 'Delete', dose, method: :delete, data: {confirm: 'Are you sure?'}, class: "my-button" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<p></p>
<%= link_to "create new dose", new_cocktail_dose_path(@cocktail), class: "btn btn-success"%>
<p></p>
<%= link_to "Back", cocktails_path %>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient, input_html: { class: "select2"} %>
    <%= f.input :amount %>
    <%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/doses/edit.html.erb
<h1>Edit Dose</h1>

<%= render 'form', dose: @dose %>

app/views/doses/new.html.erb
<h1> Add new dose to Cocktail: <%= @cocktail.name %> </h1>

<%= render 'form', dose: @dose %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>